[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(
  | venv
  | .mypy_cache
  | migrations
)/
'''
skip-string-normalization = true

[tool.flake8]
max-line-length = 120
exclude = [
    '__pycache__',
    'venv',
]

[tool.flake8.ignore]
E203 = 'whitespace before ":"'
W503 = 'line break before binary operator'
E701 = 'multiple statements on one line (colon)'

[tool.isort]
profile = 'black'
line_length = 120
known_pytest = ['pytest', 'pytest_mock']
known_aiogram = ['aiogram']
sections = [
    'FUTURE',
    'PYTEST',
    'STDLIB',
    'AIOGRAM',
    'THIRDPARTY',
    'FIRSTPARTY',
    'LOCALFOLDER'
]
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
skip = ['venv']


[tool.pytest.ini_options]
pythonpath = ['src']
norecursedirs = ['env/*', 'venv/*']
addopts = ['-s', '-v', '-p', 'no:cacheprovider']
testpaths = ['src/tests/']
python_files = ['test_*.py']

[tool.coverage.run]
omit = [
    '__init__.py',
    '*/tests/*',
]
